### ISSUE TITLE
How-to avoid repeating async with create_engine(**DB_PARAMS) as engine: .... ?

### ISSUE THREAD

**Issue by youpsla** [codelv/atom-db#13]
Hello,
this is not an issue but more an help request.

I have the following code:
```
class Model(SQLModel):
    id = Int().tag(primary_key=True)
    ........

    async def getter_1(self):
        async with create_engine(**DB_PARAMS) as engine:
            ......

    async def getter_2(self):
        async with create_engine(**DB_PARAMS) as engine:
            ......
```

Is there a way to avoid repeating `async with ....` each time ?
Sema question when request are not in the Model class but in another functions/class of my project.

(I think it's more a python question than an atom-db one but any help would be greatly appreciated)

Thanks

**Comment by frmdstryr** [comment]
The reason for needing `async with` is so it automatically closes the connection. If you want to close it / cleanup yourself you don't need to use `async with`.

You should only need to create a single "engine" (which is just a database connection pool) and assign that to the model manager (see https://github.com/codelv/atom-db#database-setup). 

After that you can use `SomeModel.objects.engine` to retrieve it, or `async with SomeModel.objects.connection() as conn:` to get a connection from the pool. 

I'd recommend also reading the [aiopg docs](https://aiopg.readthedocs.io/en/stable/) if you haven't already (or aiomysql but postges is much better in my opinion).

Not sure if that helps? Can you provide more context?

**Comment by frmdstryr** [comment]
There's also `execute`, `fetchone`, `fetchall`, and `scalar` methods of `Model.objects` which map directly to the [cursor methods](https://aiopg.readthedocs.io/en/stable/core.html#aiopg.Cursor.fetchone). 

https://github.com/codelv/atom-db/blob/master/atomdb/sql.py#L564-L647

**Comment by youpsla** [comment]
Yes, it helps.Again, thanks for your detailed answer.
I'll work with your answer and do some test, then I'll maybe have further questions.
I haven't read enough in depth aiopg docs. i'll do it.
