### ISSUE TITLE
RELATION member: Get "childs"

### ISSUE THREAD

**Issue by youpsla** [codelv/atom-db#18]
Hello,
don't know if select_related is implemented on RELATION members ?

As far I have test, it's no.
```python

class Mother(SQLModel):
    age = Int()
    childrens = RELATION(lambda: Child)

class Child(SQLModel):
    age = Int()
    mother = Instance(Mother)

# We suppose datas exist in Db

>>> m = await Mother.objects.get(_id=id)

>>> m
<commons.models.Mother at 0x105a2b8c0>

>>> m.childrens
[]

>>> c = await Child.objects.select_related('mother').get(_id=id)
>>> c
<commons.models.Child at 0x105a2b8c0>

>>>> c.mother
<commons.models.Mother at 0x105a2b8c0>
```
is it normal behaviour atm ?

**Comment by frmdstryr** [comment]
Yes, Relation does not provide any magic like django / sqlalchemy. I suppose it could automatically add itself into the list but for now you have to manually update values in a load function or something.

```py
class Mother(SQLModel):
    children = Relation(lambda: Child)
    async def load(self):
        self.children = await Child.objects.filter(mother=self)
# ...
mother = await Mother.objects.get(_id=1)
await mother.load()
```

If you know the relation will be a small set of items you can override `__restorestate__` to load it automatically. Eg 

```py
class Mother(SQLModel):
    children = Relation(lambda: Child)
    async def __restorestate__(self, state, scope=None):
        await super().__restorestate__(state, scope)
        if not self.children:
             self.children = await Child.objects.filter(mother=self)
```

But this does a query per item so it may be inefficient. 

At some point I want to make Relation return a custom list with extra methods to query/save but this is how I've been doing it.

**Comment by youpsla** [comment]
Thanks for detailed answer.
As of now, I use your first solution. I'll try the second one to have things done auto when instantiate.

**Comment by youpsla** [comment]
I have seen that using 'select_related' on he Relation member generate the right sql query:
```python
m = await Mother.objects.select_related('childrens').get(_id=id)
```

```sql
SELECT mother._id AS mother__id, mother.age AS mother_age, child._id AS child__id, child.age AS child_age
FROM mother JOIN child ON mother._id = child.mother
WHERE mother._id = %(id_1)s
```

Then, I suppose it's mainly a restore task to do. Maybe I'll try but looks complicated to/for me !!!! Let see ......

**Comment by frmdstryr** [comment]
I didn't know that, nice! I think the join in that direction required some grouping by the parent (in code), but it'd be great if there's a clean way to do it! 

[SQLQuerySet.all](https://github.com/codelv/atom-db/blob/master/atomdb/sql.py#L1216) I think would be the place to do it or maybe the sql grouping can somehow be used.

**Comment by frmdstryr** [comment]
Another thing to consider is that "through" tables may be used with a m2m relation but I don't think that should prevent it from working for the simple fk case.

I think [`prefetch_related`](https://docs.djangoproject.com/en/4.0/ref/models/querysets/#prefetch-related) would be the proper thing to add for this. Eg `Mother.objects.prefetch_related('childrens')` should populate the Relation members.

**Comment by youpsla** [comment]
In the last sentence, not sure what you mean by "that may be helpful to reference if you want to try adding it". You mean "look at other OSS async ORM to look the solution they have setup for prefetch_related (or similar)" ?

**Comment by frmdstryr** [comment]
I wasn't implying you needed to, if that's how it was taken, I apologize. I was just saying that I find it helpful to evaluate different options when they're available.

**Comment by youpsla** [comment]
As i'm considering me as a beginner regarding you concerning coding, I understood what you said more like an advise. I just wanted to be sure that the main sens is looking around what others are doing. Not necessary to apologize at all. Have a very nice WE :-)

**Comment by frmdstryr** [comment]
I didn't see any activity so I decided to implement this. If you get some time to try #20 it would be much appreciated.

Using this query should now automatically populate the `children` list. It works with `filter` and `all` as well. The cost is one additional query. 
```py
m = await Mother.objects.prefetch_related('children').get(_id=id)
```

It doesn't limit the query so if `children` happens to be a very large set it could cause some problems.

**Comment by youpsla** [comment]
Hello. I have tried but didn't achieve a correct result.
I'll try to test your PR today evening and have a close look at how you implemented it.

**Comment by frmdstryr** [comment]
Please open another issue if you have any problems with it.
